
import java.awt.Color;
import java.text.DecimalFormat;


/**
 *
 * @author CJ Powers
 * This program is a calculator for the prerequisite GPA for the information 
 * systems program at BYU. It has a location for the persons name, and areas for
 * all 7 prereq classes nessesary for the program. The user can change the number
 * of credits, as well as the grade they recieved in the class. When the user clicks
 * the "Calc GPA" button, the users GPA will appear in the right side panel,
 * as well as a color to indicate how good their GPA is. If the user clicks the 
 * reset button, then all the fields will be set to their default setting, and 
 * the focus will be set to the name field.
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderLabel = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        BUS241Label = new javax.swing.JPanel();
        EntergradeLabel = new javax.swing.JLabel();
        IS100CB = new javax.swing.JComboBox();
        IS102CB = new javax.swing.JComboBox();
        IS201CB = new javax.swing.JComboBox();
        IS303CB = new javax.swing.JComboBox();
        IS100Label = new javax.swing.JLabel();
        IS102Label = new javax.swing.JLabel();
        IS201Label = new javax.swing.JLabel();
        IS303Label = new javax.swing.JLabel();
        ACC200Label = new javax.swing.JLabel();
        FIN201Label = new javax.swing.JLabel();
        BUSM241Label = new javax.swing.JLabel();
        ACC200CB = new javax.swing.JComboBox();
        FIN201CB = new javax.swing.JComboBox();
        BUSM241CB = new javax.swing.JComboBox();
        txtIS100 = new javax.swing.JTextField();
        txtIS102 = new javax.swing.JTextField();
        txtIS201 = new javax.swing.JTextField();
        txtIS303 = new javax.swing.JTextField();
        txtACC200 = new javax.swing.JTextField();
        txtFIN201 = new javax.swing.JTextField();
        txtBUSM241 = new javax.swing.JTextField();
        Courselabel = new javax.swing.JLabel();
        CreditsLabel = new javax.swing.JLabel();
        GradeLabel = new javax.swing.JLabel();
        GPAbutton = new javax.swing.JButton();
        Resetbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        GPALabel = new javax.swing.JLabel();
        GPAcalcLabel = new javax.swing.JLabel();
        GreenPanel = new javax.swing.JPanel();
        YellowPanel = new javax.swing.JPanel();
        RedPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderLabel.setBackground(new java.awt.Color(0, 153, 204));
        HeaderLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        HeadingLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        HeadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadingLabel.setText("IS Pre-Req GPA Calculator");
        HeadingLabel.setToolTipText("");
        HeadingLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setLabelFor(NameField);
        NameLabel.setText("Enter Your Name:");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLabelLayout = new javax.swing.GroupLayout(HeaderLabel);
        HeaderLabel.setLayout(HeaderLabelLayout);
        HeaderLabelLayout.setHorizontalGroup(
            HeaderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLabelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(HeaderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeadingLabel)
                    .addGroup(HeaderLabelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        HeaderLabelLayout.setVerticalGroup(
            HeaderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLabelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(HeadingLabel)
                .addGap(18, 18, 18)
                .addGroup(HeaderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(HeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 90));

        BUS241Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EntergradeLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EntergradeLabel.setText("Enter Grades");

        IS100CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        IS100CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IS100CBActionPerformed(evt);
            }
        });

        IS102CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        IS201CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        IS303CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        IS100Label.setText("IS 100");

        IS102Label.setText("IS 102");

        IS201Label.setText("IS 201");

        IS303Label.setText("IS 303");

        ACC200Label.setText("ACC 200");

        FIN201Label.setText("FIN 201");

        BUSM241Label.setText("BUSM 241");

        ACC200CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        FIN201CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        BUSM241CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        txtIS100.setText(".5");

        txtIS102.setText(".5");

        txtIS201.setText("3");

        txtIS303.setText("3");

        txtACC200.setText("3");

        txtFIN201.setText("3");

        txtBUSM241.setText("3");
        txtBUSM241.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBUSM241ActionPerformed(evt);
            }
        });

        Courselabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        Courselabel.setText("Course");

        CreditsLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        CreditsLabel.setText("Credits");

        GradeLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        GradeLabel.setText("Grade");

        GPAbutton.setText("Calc GPA");
        GPAbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPAbuttonActionPerformed(evt);
            }
        });

        Resetbutton.setText("Reset");
        Resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BUS241LabelLayout = new javax.swing.GroupLayout(BUS241Label);
        BUS241Label.setLayout(BUS241LabelLayout);
        BUS241LabelLayout.setHorizontalGroup(
            BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BUS241LabelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BUS241LabelLayout.createSequentialGroup()
                        .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntergradeLabel)
                            .addGroup(BUS241LabelLayout.createSequentialGroup()
                                .addComponent(GPAbutton)
                                .addGap(49, 49, 49)
                                .addComponent(Resetbutton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BUS241LabelLayout.createSequentialGroup()
                        .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IS100Label)
                            .addComponent(Courselabel)
                            .addComponent(IS102Label)
                            .addComponent(IS201Label)
                            .addComponent(IS303Label)
                            .addComponent(ACC200Label)
                            .addComponent(FIN201Label)
                            .addComponent(BUSM241Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIS100, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BUS241LabelLayout.createSequentialGroup()
                                .addComponent(CreditsLabel)
                                .addGap(39, 39, 39)
                                .addComponent(GradeLabel))
                            .addComponent(txtIS102, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtACC200, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BUS241LabelLayout.createSequentialGroup()
                                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIS303, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                    .addComponent(txtIS201, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFIN201)
                                    .addComponent(txtBUSM241))
                                .addGap(54, 54, 54)
                                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IS100CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IS102CB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IS201CB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IS303CB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ACC200CB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FIN201CB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BUSM241CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))))
        );
        BUS241LabelLayout.setVerticalGroup(
            BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BUS241LabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EntergradeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Courselabel)
                    .addComponent(CreditsLabel)
                    .addComponent(GradeLabel))
                .addGap(18, 18, 18)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IS100CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIS100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IS100Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IS102CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIS102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IS102Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IS201CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIS201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IS201Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IS303CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIS303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IS303Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ACC200CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtACC200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACC200Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIN201Label)
                    .addComponent(FIN201CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFIN201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUSM241CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BUSM241Label)
                        .addComponent(txtBUSM241, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(BUS241LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPAbutton)
                    .addComponent(Resetbutton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(BUS241Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 270, 350));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        GPALabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GPALabel.setText("GPA");

        GPAcalcLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GPAcalcLabel.setText("empty");

        javax.swing.GroupLayout GreenPanelLayout = new javax.swing.GroupLayout(GreenPanel);
        GreenPanel.setLayout(GreenPanelLayout);
        GreenPanelLayout.setHorizontalGroup(
            GreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        GreenPanelLayout.setVerticalGroup(
            GreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout YellowPanelLayout = new javax.swing.GroupLayout(YellowPanel);
        YellowPanel.setLayout(YellowPanelLayout);
        YellowPanelLayout.setHorizontalGroup(
            YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        YellowPanelLayout.setVerticalGroup(
            YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RedPanelLayout = new javax.swing.GroupLayout(RedPanel);
        RedPanel.setLayout(RedPanelLayout);
        RedPanelLayout.setHorizontalGroup(
            RedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        RedPanelLayout.setVerticalGroup(
            RedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YellowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(GPALabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(GPAcalcLabel)))
                        .addGap(9, 9, 9)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(GPALabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GPAcalcLabel)
                .addGap(30, 30, 30)
                .addComponent(GreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(YellowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 190, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    double gradepoints;
    double GPA = 0;
    //declare variables
    
    public void setGPA(String course, double credits)
    //setter method for gradepoints for each class
    {
      
      
       if(course.equals("A"))
       {
           GPA = 4.0;
       }
       else if(course.equals("A-"))
       {
           GPA = 3.7;
       }
       else if(course.equals("B+"))
       {
          GPA = 3.3; 
       }
       else if(course.equals("B"))
       {
           GPA = 3;
       }
       else if(course.equals("B-"))
       {
           GPA = 2.7;
       }
       else if(course.equals("C+"))
       {
           GPA = 2.3;
       }
       else if(course.equals("C"))
       {
           GPA = 2;
       }
       else if(course.equals("C-"))
       {
           GPA = 1.7;
       }
       else if(course.equals("D+"))
       {
           GPA = 1.3;
       }
       else if(course.equals("D"))
       {
           GPA = 1;
       }
       else if(course.equals("D-"))
       {
           GPA = .7;
       }
       else if(course.equals("E"))
       {
           GPA = 0;
       }
       this.gradepoints = GPA * credits;
       //determind the gradepoints for each class
    }
    double getGPA()
    // getter method for gradepoints
    {
        return this.gradepoints;
    }
    private void IS100CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IS100CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IS100CBActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void txtBUSM241ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBUSM241ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBUSM241ActionPerformed

    private void GPAbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPAbuttonActionPerformed
        // TODO add your handling code here:

        double totalcredit = 0;
        double GPA = 0;
        DecimalFormat df = new DecimalFormat("0.00");
        //decimal format to set 2 places after decimal
        String PreReqGPA;
        //declare variables
        
        totalcredit = Double.parseDouble(txtIS100.getText())+Double.parseDouble(txtIS102.getText())+Double.parseDouble(txtIS201.getText())+Double.parseDouble(txtIS303.getText())+Double.parseDouble(txtACC200.getText())+Double.parseDouble(txtFIN201.getText())+Double.parseDouble(txtBUSM241.getText());
        //find the total number of credits 
        setGPA((String)IS100CB.getSelectedItem(), Double.parseDouble(txtIS100.getText()));
        double IS100 = getGPA();
        setGPA((String)IS102CB.getSelectedItem(), Double.parseDouble(txtIS102.getText()));
        double IS102 = getGPA();
        setGPA((String)IS201CB.getSelectedItem(), Double.parseDouble(txtIS201.getText()));
        double IS201 = getGPA();
        setGPA((String)IS303CB.getSelectedItem(), Double.parseDouble(txtIS303.getText()));
        double IS303 = getGPA();
        setGPA((String)ACC200CB.getSelectedItem(), Double.parseDouble(txtACC200.getText()));
        double ACC200 = getGPA();
        setGPA((String)FIN201CB.getSelectedItem(), Double.parseDouble(txtFIN201.getText()));
        double FIN201 = getGPA();
        setGPA((String)BUSM241CB.getSelectedItem(), Double.parseDouble(txtBUSM241.getText()));
        double BUSM241 = getGPA();
        //calculate the gradepoints for each class
        GPA = (IS100 + IS102 + IS201 + IS303 + ACC200 + FIN201 + BUSM241) / totalcredit;
        //this will calculate the GPA in a number format
        String newGPA = df.format(GPA);
        //convert the number GPA into a string with the decimal format to 2 places
        GPAcalcLabel.setText(newGPA);
        //set the text for the GPA label
        if(GPA >=3.7)
        {
            GreenPanel.setBackground(Color.green);
            YellowPanel.setBackground(new Color(214, 217, 223));
            RedPanel.setBackground(new Color(214, 217, 223));
        }
        else if(GPA >= 3.2)
        {
            GreenPanel.setBackground(new Color(214, 217, 223));
            YellowPanel.setBackground(Color.yellow);
            RedPanel.setBackground(new Color(214, 217, 223));
        }
        else
        {
            GreenPanel.setBackground(new Color(214, 217, 223));
            YellowPanel.setBackground(new Color(214, 217, 223));
            RedPanel.setBackground(Color.red); 
        }
        //these if statements will determine which color should appear
    }//GEN-LAST:event_GPAbuttonActionPerformed

    private void ResetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbuttonActionPerformed
        // TODO add your handling code here:
        GPAcalcLabel.setText("0.00");
        NameField.setText("");
        txtIS100.setText(".5");
        txtIS102.setText(".5");
        txtIS201.setText("3");
        txtIS303.setText("3");
        txtACC200.setText("3");
        txtFIN201.setText("3");
        txtBUSM241.setText("3");
        IS100CB.setSelectedIndex(0);
        IS102CB.setSelectedIndex(0);
        IS201CB.setSelectedIndex(0);
        IS303CB.setSelectedIndex(0);
        ACC200CB.setSelectedIndex(0);
        FIN201CB.setSelectedIndex(0);
        BUSM241CB.setSelectedIndex(0);
        GreenPanel.setBackground(new Color(214, 217, 223));
        YellowPanel.setBackground(new Color(214, 217, 223));
        RedPanel.setBackground(new Color(214, 217, 223));
        NameField.requestFocus();
        //this resets all of the fields and set the name field as the focus
    }//GEN-LAST:event_ResetbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ACC200CB;
    private javax.swing.JLabel ACC200Label;
    private javax.swing.JPanel BUS241Label;
    private javax.swing.JComboBox BUSM241CB;
    private javax.swing.JLabel BUSM241Label;
    private javax.swing.JLabel Courselabel;
    private javax.swing.JLabel CreditsLabel;
    private javax.swing.JLabel EntergradeLabel;
    private javax.swing.JComboBox FIN201CB;
    private javax.swing.JLabel FIN201Label;
    private javax.swing.JLabel GPALabel;
    private javax.swing.JButton GPAbutton;
    private javax.swing.JLabel GPAcalcLabel;
    private javax.swing.JLabel GradeLabel;
    private javax.swing.JPanel GreenPanel;
    private javax.swing.JPanel HeaderLabel;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JComboBox IS100CB;
    private javax.swing.JLabel IS100Label;
    private javax.swing.JComboBox IS102CB;
    private javax.swing.JLabel IS102Label;
    private javax.swing.JComboBox IS201CB;
    private javax.swing.JLabel IS201Label;
    private javax.swing.JComboBox IS303CB;
    private javax.swing.JLabel IS303Label;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel RedPanel;
    private javax.swing.JButton Resetbutton;
    private javax.swing.JPanel YellowPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtACC200;
    private javax.swing.JTextField txtBUSM241;
    private javax.swing.JTextField txtFIN201;
    private javax.swing.JTextField txtIS100;
    private javax.swing.JTextField txtIS102;
    private javax.swing.JTextField txtIS201;
    private javax.swing.JTextField txtIS303;
    // End of variables declaration//GEN-END:variables
}
