import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CJ Powers
 * 
 * This program simulates a list of conference and non conference teams playing
 * a series of basketball games. Each conference team will play every team in the
 * conference twice, once as home team, and once as away. If the +5 bonus check 
 * box is checked, then the home team will get 5 points extra. Each conference team
 * will play each non conference team once. The conference teams are then sorted
 * from most wins to least wins. The name, wins, losses, and status are then
 * printed.
 */

class team
{
    int wins;
    int losses;
    String name;
    double winlosspct;
    String status;
    //declare variables
    
    //constructor
    public team(String name)
    {
        this.name = name;
        this.wins = 0;
        this.losses= 0;
        this.winlosspct = 0;
    }
     
    //getters
    
    public String getteamname()
    {
        return this.name;
        //return the number of wins
    }
    public int getwins()
    {
        return this.wins;
    }
    public int getlosses()
    {
        return this.losses;
        //return the number of losses
    }
    public double getwinlosspct()
    {
        return this.getwinlosspct();
        //return the win loss percent
    }
    
    //setters
    public void addwin()
    {
        this.wins += 1;
        //add a win to team
    }
    public void addloss()
    {
        this.losses += 1;
        //add a loss to team
    }
    public void calcwinlosspct()
    {
        int total = this.wins + this.losses;
        this.winlosspct = (double) this.wins/ (double) total;
        //calcs win loss percent
    }
    public void setstatus()
    {
        if(this.wins >= 20)
        {
            this.status = "March Madness";          
        }
        else if(this.wins >= 15)
        {
            this.status = "NIT";
        }
        else
        {
            this.status = "See you next year";
        }
        //determine status
    }
    
    public String getstatus()
    {   
        return status;
        //returns a string with the status
    }

}
public class main extends javax.swing.JFrame {


    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtstatus = new javax.swing.JLabel();
        txtlosses = new javax.swing.JLabel();
        txtwins = new javax.swing.JLabel();
        txtRecord = new javax.swing.JLabel();
        txtteam1 = new javax.swing.JLabel();
        txtteam2 = new javax.swing.JLabel();
        txtteam3 = new javax.swing.JLabel();
        txtteam4 = new javax.swing.JLabel();
        txtteam5 = new javax.swing.JLabel();
        txtteam6 = new javax.swing.JLabel();
        txtteam7 = new javax.swing.JLabel();
        txtteam8 = new javax.swing.JLabel();
        txtteam9 = new javax.swing.JLabel();
        txtteam10 = new javax.swing.JLabel();
        txtstatus1 = new javax.swing.JLabel();
        txtstatus2 = new javax.swing.JLabel();
        txtstatus3 = new javax.swing.JLabel();
        txtstatus4 = new javax.swing.JLabel();
        txtstatus5 = new javax.swing.JLabel();
        txtstatus6 = new javax.swing.JLabel();
        txtstatus7 = new javax.swing.JLabel();
        txtstatus8 = new javax.swing.JLabel();
        txtstatus9 = new javax.swing.JLabel();
        txtstatus10 = new javax.swing.JLabel();
        txtlosses1 = new javax.swing.JLabel();
        txtlosses2 = new javax.swing.JLabel();
        txtlosses3 = new javax.swing.JLabel();
        txtlosses4 = new javax.swing.JLabel();
        txtlosses5 = new javax.swing.JLabel();
        txtlosses6 = new javax.swing.JLabel();
        txtlosses7 = new javax.swing.JLabel();
        txtlosses8 = new javax.swing.JLabel();
        txtlosses9 = new javax.swing.JLabel();
        txtlosses10 = new javax.swing.JLabel();
        txtwins1 = new javax.swing.JLabel();
        txtwins2 = new javax.swing.JLabel();
        txtwins3 = new javax.swing.JLabel();
        txtwins4 = new javax.swing.JLabel();
        txtwins5 = new javax.swing.JLabel();
        txtwins6 = new javax.swing.JLabel();
        txtwins7 = new javax.swing.JLabel();
        txtwins8 = new javax.swing.JLabel();
        txtwins9 = new javax.swing.JLabel();
        txtwins10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtconference = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listconference = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listnonconference = new javax.swing.JList();
        txtnonconference = new javax.swing.JLabel();
        btnplay = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnquit = new javax.swing.JButton();
        cbhometeam = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtstatus.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtstatus.setText("Status");

        txtlosses.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtlosses.setText("Losses");

        txtwins.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtwins.setText("Wins");

        txtRecord.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtRecord.setText("Record");

        txtteam1.setText(" ");

        txtteam2.setText("           ");

        txtteam3.setText("             ");

        txtteam4.setText("                   ");

        txtteam5.setText("                   ");

        txtteam6.setText("               ");

        txtteam7.setText("               ");

        txtteam8.setText("              ");

        txtteam9.setText("                 ");

        txtteam10.setText("               ");

        txtstatus1.setText("       ");

        txtstatus2.setText("     ");

        txtstatus3.setText("          ");

        txtstatus4.setText("         ");

        txtstatus5.setText("           ");

        txtstatus6.setText("          ");

        txtstatus7.setText("              ");

        txtstatus8.setText("           ");

        txtstatus9.setText("           ");

        txtstatus10.setText("       ");

        txtlosses1.setText("      ");

        txtlosses2.setText("      ");

        txtlosses3.setText("      ");

        txtlosses4.setText("      ");

        txtlosses5.setText("      ");

        txtlosses6.setText("      ");

        txtlosses7.setText("      ");

        txtlosses8.setText("      ");

        txtlosses9.setText("      ");

        txtlosses10.setText("      ");

        txtwins2.setText("      ");

        txtwins3.setText("      ");

        txtwins4.setText("      ");

        txtwins5.setText("      ");

        txtwins6.setText("      ");

        txtwins7.setText("      ");

        txtwins8.setText("      ");

        txtwins9.setText("      ");

        txtwins10.setText("      ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtRecord))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtteam1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txtteam5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteam10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtwins)
                    .addComponent(txtwins1)
                    .addComponent(txtwins2)
                    .addComponent(txtwins3)
                    .addComponent(txtwins4)
                    .addComponent(txtwins5)
                    .addComponent(txtwins6)
                    .addComponent(txtwins7)
                    .addComponent(txtwins8)
                    .addComponent(txtwins9)
                    .addComponent(txtwins10))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtlosses)
                    .addComponent(txtlosses1)
                    .addComponent(txtlosses2)
                    .addComponent(txtlosses3)
                    .addComponent(txtlosses4)
                    .addComponent(txtlosses5)
                    .addComponent(txtlosses6)
                    .addComponent(txtlosses7)
                    .addComponent(txtlosses8)
                    .addComponent(txtlosses9)
                    .addComponent(txtlosses10))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtstatus)
                    .addComponent(txtstatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtstatus8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtstatus10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstatus)
                    .addComponent(txtlosses)
                    .addComponent(txtwins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam1)
                    .addComponent(txtstatus1)
                    .addComponent(txtlosses1)
                    .addComponent(txtwins1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam2)
                    .addComponent(txtstatus2)
                    .addComponent(txtlosses2)
                    .addComponent(txtwins2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam3)
                    .addComponent(txtstatus3)
                    .addComponent(txtlosses3)
                    .addComponent(txtwins3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam4)
                    .addComponent(txtstatus4)
                    .addComponent(txtlosses4)
                    .addComponent(txtwins4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam5)
                    .addComponent(txtstatus5)
                    .addComponent(txtlosses5)
                    .addComponent(txtwins5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam6)
                    .addComponent(txtstatus6)
                    .addComponent(txtlosses6)
                    .addComponent(txtwins6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam7)
                    .addComponent(txtstatus7)
                    .addComponent(txtlosses7)
                    .addComponent(txtwins7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam8)
                    .addComponent(txtstatus8)
                    .addComponent(txtlosses8)
                    .addComponent(txtwins8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam9)
                    .addComponent(txtstatus9)
                    .addComponent(txtlosses9)
                    .addComponent(txtwins9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtteam10)
                    .addComponent(txtstatus10)
                    .addComponent(txtlosses10)
                    .addComponent(txtwins10))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 420, 290));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtconference.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtconference.setText("Conference Teams");

        listconference.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "BYU", "Gonzaga", "Loyola", "St. Marys", "Pepperdine", "San Francisco", "San Diego", "Portland", "Pacific", "Santa Clara" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listconference.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listconference.setToolTipText("");
        jScrollPane1.setViewportView(listconference);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtconference)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtconference)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listnonconference.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Arizona", "Florida", "Memphis", "Stanford", "Dayton", "Texas" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listnonconference);

        txtnonconference.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnonconference.setText("Non-Conference Teams");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtnonconference)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtnonconference)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 160, 180));

        btnplay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnplay.setText("Play");
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        btnquit.setText("Quit");
        btnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitActionPerformed(evt);
            }
        });
        getContentPane().add(btnquit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        cbhometeam.setText("Home Team +5");
        getContentPane().add(cbhometeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
        Random scoregenerator = new Random();
        
        team[] conference = new team[listconference.getModel().getSize()];
        //new array of conference teams
        int icount;
        
        for (icount = 0; icount < conference.length; icount++)
        {
            listconference.setSelectedIndex(icount);
            conference[icount] = new team (listconference.getSelectedValue().toString());
            //create object
        }
        team[] nonconference = new team [listnonconference.getModel().getSize()];
        //create an array of nonconference teams
        
        for (icount = 0; icount < nonconference.length; icount++)
        {
            listnonconference.setSelectedIndex(icount);
            nonconference[icount] = new team (listnonconference.getSelectedValue().toString());
            //create an object
        }
        //conference gameplay
        for (int ihome = 0; ihome < conference.length; ihome++)
        {   
            for (int iaway = 0; iaway<conference.length; iaway++)
            {
                int homescore = 0;
                int awayscore = 0;
                
                if(ihome != iaway)
                {
                    while (homescore == awayscore)
                    //dont allow ties
                    {
                        homescore =scoregenerator.nextInt(101);
                        awayscore = scoregenerator.nextInt(101);
                        //generate a random score for both teams
                        
                        if (cbhometeam.isSelected())
                        {
                           homescore += 5; 
                           //home team gets 5 bonus points
                        }
                    }
                    if (homescore > awayscore)
                    {
                        conference[ihome].addwin();
                        conference[iaway].addloss();
                        //add win for home team
                    }
                    else
                    {
                        conference[iaway].addwin();
                        conference[ihome].addloss();
                        //add win for away team
                    }
                }
            }      
                
        }
        //nonconference gameplay
        for(int icon = 0; icon < conference.length; icon++)
        {
           for (int inon = 0; inon < nonconference.length; inon++)
           {
               int nonpoints = 0;
               int conpoints = 0;
               while(conpoints == nonpoints)
               //dont allow for ties
               {
                   conpoints = scoregenerator.nextInt(101);
                   nonpoints = scoregenerator.nextInt(101);
                   //generate random scores for each team
               }
               if(conpoints >nonpoints)
               {
                   conference[icon].addwin();
                   nonconference[inon].addloss();
                   //add win to conference team
               }
               else
               {
                   conference[icon].addloss();
                   nonconference[inon].addwin();
                   //add win to non conference team
               }
           }
        }
        
        //calc win/loss
        for(int i = 0; i<conference.length; i++)
        {
            conference[i].calcwinlosspct();
            conference[i].setstatus();
        }
        
        //sort
        int iSort1;
        int iSort2;
        team holder[] = new team[1];
        for (iSort1 = 0; iSort1 < conference.length; iSort1++)
        {
            for (iSort2 = conference.length-1; iSort2 > iSort1; iSort2--)
            {
                if (conference[iSort2-1].getwins() < conference[iSort2].getwins())
                {
                    holder[0] = conference[iSort2-1];
                    //move to temp location
                    conference[iSort2-1] = conference[iSort2];
                    conference[iSort2] = holder[0];
                    //move temp value to second place
                }
            }
        }
        //Set the names 
       txtteam1.setText(conference[0].getteamname()); 
       txtteam2.setText(conference[1].getteamname());
       txtteam3.setText(conference[2].getteamname());
       txtteam4.setText(conference[3].getteamname());
       txtteam5.setText(conference[4].getteamname());
       txtteam6.setText(conference[5].getteamname());
       txtteam7.setText(conference[6].getteamname());
       txtteam8.setText(conference[7].getteamname());
       txtteam9.setText(conference[8].getteamname());
       txtteam10.setText(conference[9].getteamname());
       
       //set the wins
       txtwins1.setText(Integer.toString(conference[0].getwins()));
       txtwins2.setText(Integer.toString(conference[1].getwins()));
       txtwins3.setText(Integer.toString(conference[2].getwins()));
       txtwins4.setText(Integer.toString(conference[3].getwins()));
       txtwins5.setText(Integer.toString(conference[4].getwins()));
       txtwins6.setText(Integer.toString(conference[5].getwins()));
       txtwins7.setText(Integer.toString(conference[6].getwins()));
       txtwins8.setText(Integer.toString(conference[7].getwins()));
       txtwins9.setText(Integer.toString(conference[8].getwins()));
       txtwins10.setText(Integer.toString(conference[9].getwins()));
       
       //set the statuses
       txtstatus1.setText(conference[0].getstatus());
       txtstatus2.setText(conference[1].getstatus());
       txtstatus3.setText(conference[2].getstatus());
       txtstatus4.setText(conference[3].getstatus());
       txtstatus5.setText(conference[4].getstatus());
       txtstatus6.setText(conference[5].getstatus());
       txtstatus7.setText(conference[6].getstatus());
       txtstatus8.setText(conference[7].getstatus());
       txtstatus9.setText(conference[8].getstatus());
       txtstatus10.setText(conference[9].getstatus());
       
       //set the losses
       txtlosses1.setText(Integer.toString(conference[0].getlosses())); 
       txtlosses2.setText(Integer.toString(conference[1].getlosses()));
       txtlosses3.setText(Integer.toString(conference[2].getlosses()));
       txtlosses4.setText(Integer.toString(conference[3].getlosses()));
       txtlosses5.setText(Integer.toString(conference[4].getlosses()));
       txtlosses6.setText(Integer.toString(conference[5].getlosses()));
       txtlosses7.setText(Integer.toString(conference[6].getlosses()));
       txtlosses8.setText(Integer.toString(conference[7].getlosses()));
       txtlosses9.setText(Integer.toString(conference[8].getlosses()));
       txtlosses10.setText(Integer.toString(conference[9].getlosses()));
        
    }//GEN-LAST:event_btnplayActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
       //set losses to blank
        txtlosses1.setText(""); 
       txtlosses2.setText("");
       txtlosses3.setText("");
       txtlosses4.setText("");
       txtlosses5.setText("");
       txtlosses6.setText("");
       txtlosses7.setText("");
       txtlosses8.setText("");
       txtlosses9.setText("");
       txtlosses10.setText("");
       
       //set wins to blank
       txtwins1.setText("");
       txtwins2.setText("");
       txtwins3.setText("");
       txtwins4.setText("");
       txtwins5.setText("");
       txtwins6.setText("");
       txtwins7.setText("");
       txtwins8.setText("");
       txtwins9.setText("");
       txtwins10.setText("");
       
       //set statuses to blank
       txtstatus1.setText("");
       txtstatus2.setText("");
       txtstatus3.setText("");
       txtstatus4.setText("");
       txtstatus5.setText("");
       txtstatus6.setText("");
       txtstatus7.setText("");
       txtstatus8.setText("");
       txtstatus9.setText("");
       txtstatus10.setText("");
       
       //set team names to blank
       txtteam1.setText("");
       txtteam2.setText("");
       txtteam3.setText("");
       txtteam4.setText("");
       txtteam5.setText("");
       txtteam6.setText("");
       txtteam7.setText("");
       txtteam8.setText("");
       txtteam9.setText("");
       txtteam10.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitActionPerformed
        //exit the program
        System.exit(0);
    }//GEN-LAST:event_btnquitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnquit;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cbhometeam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listconference;
    private javax.swing.JList listnonconference;
    private javax.swing.JLabel txtRecord;
    private javax.swing.JLabel txtconference;
    private javax.swing.JLabel txtlosses;
    private javax.swing.JLabel txtlosses1;
    private javax.swing.JLabel txtlosses10;
    private javax.swing.JLabel txtlosses2;
    private javax.swing.JLabel txtlosses3;
    private javax.swing.JLabel txtlosses4;
    private javax.swing.JLabel txtlosses5;
    private javax.swing.JLabel txtlosses6;
    private javax.swing.JLabel txtlosses7;
    private javax.swing.JLabel txtlosses8;
    private javax.swing.JLabel txtlosses9;
    private javax.swing.JLabel txtnonconference;
    private javax.swing.JLabel txtstatus;
    private javax.swing.JLabel txtstatus1;
    private javax.swing.JLabel txtstatus10;
    private javax.swing.JLabel txtstatus2;
    private javax.swing.JLabel txtstatus3;
    private javax.swing.JLabel txtstatus4;
    private javax.swing.JLabel txtstatus5;
    private javax.swing.JLabel txtstatus6;
    private javax.swing.JLabel txtstatus7;
    private javax.swing.JLabel txtstatus8;
    private javax.swing.JLabel txtstatus9;
    private javax.swing.JLabel txtteam1;
    private javax.swing.JLabel txtteam10;
    private javax.swing.JLabel txtteam2;
    private javax.swing.JLabel txtteam3;
    private javax.swing.JLabel txtteam4;
    private javax.swing.JLabel txtteam5;
    private javax.swing.JLabel txtteam6;
    private javax.swing.JLabel txtteam7;
    private javax.swing.JLabel txtteam8;
    private javax.swing.JLabel txtteam9;
    private javax.swing.JLabel txtwins;
    private javax.swing.JLabel txtwins1;
    private javax.swing.JLabel txtwins10;
    private javax.swing.JLabel txtwins2;
    private javax.swing.JLabel txtwins3;
    private javax.swing.JLabel txtwins4;
    private javax.swing.JLabel txtwins5;
    private javax.swing.JLabel txtwins6;
    private javax.swing.JLabel txtwins7;
    private javax.swing.JLabel txtwins8;
    private javax.swing.JLabel txtwins9;
    // End of variables declaration//GEN-END:variables
}
